In [0]:
### IMPORTAÇÃO DAS BIBLIOTECAS ###

import matplotlib.pyplot as plt # importação da biblioteca matplotlib
import numpy as np # importação da biblioteca numpy 
import seaborn as sns # importação da biblioteca seaborn
import pandas as pd # importação da biblioteca pandas

from sklearn import preprocessing
import sklearn

# Divide arrays ou matrizes em subconjuntos aleatórios de treino e teste
from sklearn.model_selection import train_test_split # importação da biblioteca de treino e teste
from sklearn.linear_model import LogisticRegression # importação do algoritmo de Regressão Logística
from sklearn.metrics import accuracy_score # importação da biblioteca de medir a acurácia do algoritmo de ML

from sklearn.metrics import confusion_matrix # importação do algoritmo de Matrix de Confusão
from sklearn.metrics import classification_report 
from sklearn.svm import LinearSVC # importação da biblioteca LinearSVC

import time # importação da biblioteca para calcular o tempo de execução de um trecho do código

# Le o arquivo do dataset
originalDS = pd.read_csv("weatherHistory.csv", encoding ='latin1')
df = originalDS.copy()

# Converte a coluna 'Precip Type' em inteiros
precip_type = df.replace(["rain","snow",np.nan],[0,1,2])
df = precip_type

# Separando as features principais
df = df[['Temperature (C)', 
         'Humidity',
         'Pressure (millibars)', 
         'Precip Type']]

# Defining axis
X = df[['Temperature (C)','Pressure (millibars)','Humidity']] 
y = df[['Precip Type']]

In [0]:
# Separando o dataset em variáveis de treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.22, random_state=42)

# Instancia o algoritmo de Regressão Logística
lr = LogisticRegression(max_iter=1000, solver="lbfgs")

# Treina o algoritmo e tenta prever resultados
start = time.time()
lr.fit(X_treino, y_treino)
predict = lr.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)

print('\n\n* Time in seconds: %d' % (time.time() - start))
print("Accuracy: %.2f" % (accuracy * 100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




* Time in seconds: 4
Accuracy: 99.26


In [0]:
confusion_matrix(y_teste, predict)


array([[18646,    34,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
confusion_matrix(y_teste, predict)


array([[18648,    32,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.67      0.66     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.67      0.66     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
# Instancia o algoritmo LinearSVC
linearSVC = LinearSVC()

# Treina e testa o algoritmo LinearSVC
start = time.time()
linearSVC.fit(X_treino, y_treino)
predict = linearSVC.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)

print('\n\n* Time in seconds: %d' % (time.time() - start))
print("Accuracy: %.2f" % (accuracy * 100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




* Time in seconds: 7
Accuracy: 98.05


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [0]:
confusion_matrix(y_teste, predict)

array([[18390,   290,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     18680
           1       0.89      1.00      0.94      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.98     21220
   macro avg       0.63      0.66      0.64     21220
weighted avg       0.98      0.98      0.98     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
logreg = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'multi_class': ['ovr', 'multinomial'],

}

linsvm = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1', 'l2' ],
    'multi_class': ['ovr', 'multinomial'],

}

In [0]:
from sklearn.model_selection import GridSearchCV

lr = LogisticRegression(solver='saga')
svm = LinearSVC()

In [0]:
grid_lr = GridSearchCV(lr, logreg)
grid_lr.fit(X_treino, y_treino)

predict = gird_lr.predict(X_teste)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y

NameError: ignored

In [0]:
confusion_matrix(y_teste, predict)

array([[18390,   290,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     18680
           1       0.89      1.00      0.94      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.98     21220
   macro avg       0.63      0.66      0.64     21220
weighted avg       0.98      0.98      0.98     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
#grid_svm = GridSearchCV(svm, linsvm)
#grid_svm.fit(X_treino, y_treino)

predict = grid_svm.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)
accuracy

0.991894439208294

In [0]:
confusion_matrix(y_teste, predict)

array([[18638,    19,    23],
       [    3,  2410,     4],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.66      0.66     21220
weighted avg       0.99      0.99      0.99     21220



In [0]:
grid_lr.best_params_

{'C': 100.0, 'multi_class': 'multinomial', 'penalty': 'l1', 'tol': 0.0001}

In [0]:
grid_svm.best_params_

{'C': 10.0,
 'loss': 'hinge',
 'multi_class': 'ovr',
 'penalty': 'l2',
 'tol': 0.0001}

Busca features
One-vs-All (grid e features)
Rebalanceamento
Remapeamento "Daily Summary" (esparcidade)

---

{'C': 10.0,
 'loss': 'hinge',
 'multi_class': 'ovr',
 'penalty': 'l2',
 'tol': 0.0001}