In [0]:
### IMPORTAÇÃO DAS BIBLIOTECAS ###

import matplotlib.pyplot as plt # importação da biblioteca matplotlib
import numpy as np # importação da biblioteca numpy 
import seaborn as sns # importação da biblioteca seaborn
import pandas as pd # importação da biblioteca pandas

from sklearn import preprocessing
import sklearn

# Divide arrays ou matrizes em subconjuntos aleatórios de treino e teste
from sklearn.model_selection import train_test_split # importação da biblioteca de treino e teste
from sklearn.linear_model import LogisticRegression # importação do algoritmo de Regressão Logística
from sklearn.metrics import accuracy_score # importação da biblioteca de medir a acurácia do algoritmo de ML

from sklearn.metrics import confusion_matrix # importação do algoritmo de Matrix de Confusão
from sklearn.metrics import classification_report 
from sklearn.svm import LinearSVC # importação da biblioteca LinearSVC

import time # importação da biblioteca para calcular o tempo de execução de um trecho do código

# Le o arquivo do dataset
originalDS = pd.read_csv("weatherHistory.csv", encoding ='latin1')
df = originalDS.copy()

# Converte a coluna 'Precip Type' em inteiros
precip_type = df.replace(["rain","snow",np.nan],[0,1,2])
df = precip_type

# Separando as features principais
df = df[['Temperature (C)', 
         'Humidity',
         'Pressure (millibars)', 
         'Precip Type']]

# Defining axis
X = df[['Temperature (C)','Pressure (millibars)','Humidity']] 
y = df[['Precip Type']]

In [0]:
# Separando o dataset em variáveis de treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.22, random_state=42)

# Instancia o algoritmo de Regressão Logística
lr = LogisticRegression(max_iter=1000, solver="lbfgs")

# Treina o algoritmo e tenta prever resultados
start = time.time()
lr.fit(X_treino, y_treino)
predict = lr.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)

print('\n\n* Time in seconds: %d' % (time.time() - start))
print("Accuracy: %.2f" % (accuracy * 100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




* Time in seconds: 4
Accuracy: 99.26


In [0]:
confusion_matrix(y_teste, predict)


array([[18646,    34,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
confusion_matrix(y_teste, predict)


array([[18648,    32,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.67      0.66     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.67      0.66     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
# Instancia o algoritmo LinearSVC
linearSVC = LinearSVC()

# Treina e testa o algoritmo LinearSVC
start = time.time()
linearSVC.fit(X_treino, y_treino)
predict = linearSVC.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)

print('\n\n* Time in seconds: %d' % (time.time() - start))
print("Accuracy: %.2f" % (accuracy * 100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




* Time in seconds: 7
Accuracy: 98.05


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [0]:
confusion_matrix(y_teste, predict)

array([[18390,   290,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     18680
           1       0.89      1.00      0.94      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.98     21220
   macro avg       0.63      0.66      0.64     21220
weighted avg       0.98      0.98      0.98     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
logreg = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'multi_class': ['ovr', 'multinomial'],

}

linsvm = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1', 'l2' ],
    'multi_class': ['ovr', 'multinomial'],

}

In [0]:
from sklearn.model_selection import GridSearchCV

lr = LogisticRegression(solver='saga')
svm = LinearSVC()

In [0]:
grid_lr = GridSearchCV(lr, logreg)
grid_lr.fit(X_treino, y_treino)

predict = gird_lr.predict(X_teste)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y

NameError: ignored

In [0]:
confusion_matrix(y_teste, predict)

array([[18390,   290,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     18680
           1       0.89      1.00      0.94      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.98     21220
   macro avg       0.63      0.66      0.64     21220
weighted avg       0.98      0.98      0.98     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
#grid_svm = GridSearchCV(svm, linsvm)
#grid_svm.fit(X_treino, y_treino)

predict = grid_svm.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)
accuracy

0.991894439208294

In [0]:
confusion_matrix(y_teste, predict)

array([[18638,    19,    23],
       [    3,  2410,     4],
       [  123,     0,     0]])

In [0]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.66      0.66     21220
weighted avg       0.99      0.99      0.99     21220



In [0]:
grid_lr.best_params_

{'C': 100.0, 'multi_class': 'multinomial', 'penalty': 'l1', 'tol': 0.0001}

In [0]:
grid_svm.best_params_

{'C': 10.0,
 'loss': 'hinge',
 'multi_class': 'ovr',
 'penalty': 'l2',
 'tol': 0.0001}

Busca features 
One-vs-All (grid e features)
Rebalanceamento
Remapeamento "Daily Summary" (esparcidade)

---

{'C': 10.0,
 'loss': 'hinge',
 'multi_class': 'ovr',
 'penalty': 'l2',
 'tol': 0.0001}

array(['Partly cloudy throughout the day.',
       'Mostly cloudy throughout the day.', 'Foggy in the evening.',
       'Foggy overnight and breezy in the morning.',
       'Overcast throughout the day.', 'Partly cloudy until night.',
       'Mostly cloudy until night.',
       'Foggy starting overnight continuing until morning.',
       'Foggy in the morning.', 'Partly cloudy until evening.',
       'Partly cloudy starting in the morning.',
       'Mostly cloudy starting overnight continuing until night.',
       'Mostly cloudy until evening.',
       'Partly cloudy starting in the morning continuing until evening.',
       'Partly cloudy starting in the afternoon.',
       'Partly cloudy starting overnight.',
       'Partly cloudy until morning.',
       'Partly cloudy starting overnight continuing until night.',
       'Partly cloudy starting in the afternoon continuing until night.',
       'Mostly cloudy starting overnight.',
       'Partly cloudy until afternoon.',
       'Mostly

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
df0 = df.copy()
df1 = df.copy()
df2 = df.copy()

In [29]:

df0['Precip Type'] = df0['Precip Type'].apply(lambda x: 0 if x == 0 else 1)
df0['Precip Type'].unique()

array([0, 1])

In [30]:
df1['Precip Type'] = df1['Precip Type'].apply(lambda x: 1 if x == 1 else 0)
df1['Precip Type'].unique()

array([0, 1])

In [31]:
df2['Precip Type'] = df2['Precip Type'].apply(lambda x: 2 if x == 2 else 0)
df2['Precip Type'].unique()

array([0, 2])

In [33]:
X0 = df0[['Temperature (C)','Pressure (millibars)','Humidity']] 
y0 = df0[['Precip Type']]

X_treino0, X_teste0, y_treino0, y_teste0 = train_test_split(X0, y0, test_size=0.22, random_state=40)

linsvm0 = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1', 'l2' ],
    # 'multi_class': ['ovr', 'multinomial'],

}

svm0 = LinearSVC()

grid_svm0 = GridSearchCV(svm0, linsvm0)
grid_svm0.fit(X_treino0, y_treino0)

predict0 = grid_svm.predict(X_teste0)
accuracy0 = accuracy_score(y_teste0, predict0)
print(accuracy0)

print(confusion_matrix(y_teste0, predict0))

print(classification_report(y_teste0, predict0))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='hinge' is not supported, Parameters: penalty='l1', loss='hinge', dual=True

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: Fi

0.8846371347785108
[[18772     0]
 [ 2448     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     18772
           1       0.00      0.00      0.00      2448

    accuracy                           0.88     21220
   macro avg       0.44      0.50      0.47     21220
weighted avg       0.78      0.88      0.83     21220



/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
X1 = df1[['Temperature (C)','Pressure (millibars)','Humidity']] 
y1 = df1[['Precip Type']]

X_treino1, X_teste1, y_treino1, y_teste1 = train_test_split(X1, y1, test_size=0.22, random_state=42)

linsvm1 = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1', 'l2' ],
    # 'multi_class': ['ovr', 'multinomial'],

}

svm1 = LinearSVC()

grid_svm1 = GridSearchCV(svm1, linsvm1)
grid_svm.fit(X_treino1, y_treino1)

predict1 = grid_svm.predict(X_teste1)
accuracy1 = accuracy_score(y_teste1, predict1)
print(accuracy1)

print(confusion_matrix(y_teste1, predict1))

print(classification_report(y_teste1, predict1))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='hinge' is not supported, Parameters: penalty='l1', loss='hinge', dual=True

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: Fi

0.9952874646559849
[[18803     0]
 [  100  2317]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18803
           1       1.00      0.96      0.98      2417

    accuracy                           1.00     21220
   macro avg       1.00      0.98      0.99     21220
weighted avg       1.00      1.00      1.00     21220



/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [35]:
X2 = df2[['Temperature (C)','Pressure (millibars)','Humidity']] 
y2 = df2[['Precip Type']]

X_treino2, X_teste2, y_treino2, y_teste2 = train_test_split(X2, y2, test_size=0.22, random_state=42)

linsvm2 = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1', 'l2' ],
    # 'multi_class': ['ovr', 'multinomial'],

}

svm2 = LinearSVC()

grid_svm2 = GridSearchCV(svm2, linsvm2)
grid_svm.fit(X_treino2, y_treino2)

predict2 = grid_svm.predict(X_teste2)
accuracy2 = accuracy_score(y_teste2, predict2)
print(accuracy2)

print(confusion_matrix(y_teste2, predict2))

print(classification_report(y_teste2, predict2))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='hinge' is not supported, Parameters: penalty='l1', loss='hinge', dual=True

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: Fi

0.9942035815268615
[[21097     0]
 [  123     0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     21097
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.50      0.50      0.50     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [24]:
grid_svm.best_params_

{'C': 0.01, 'loss': 'hinge', 'penalty': 'l2', 'tol': 0.001}

{'C': 10.0, 'loss': 'hinge', 'multi_class': 'ovr', 'penalty': 'l2', 'tol': 0.0001}

In [26]:
X = df2[['Temperature (C)','Pressure (millibars)','Humidity']] 
y = df2[['Precip Type']]

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.22, random_state=42)

svm2 = LinearSVC(C=10.0, loss='hinge', penalty= 'l2', tol=0.0001)
                 
predict = grid_svm.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)
print(accuracy)

print(confusion_matrix(y_teste, predict))

print(classification_report(y_teste, predict))

0.9942035815268615
[[21097     0]
 [  123     0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     21097
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.50      0.50      0.50     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
df.head()

Temperature (C)  Humidity  Pressure (millibars)  Precip Type
0         9.472222      0.89               1015.13            0
1         9.355556      0.86               1015.63            0
2         9.377778      0.89               1015.94            0
3         8.288889      0.83               1016.41            0
4         8.755556      0.83               1016.51            0