In [0]:
### IMPORTAÇÃO DAS BIBLIOTECAS ###

import matplotlib.pyplot as plt # importação da biblioteca matplotlib
import numpy as np # importação da biblioteca numpy 
import seaborn as sns # importação da biblioteca seaborn
import pandas as pd # importação da biblioteca pandas

from sklearn import preprocessing
import sklearn

# Divide arrays ou matrizes em subconjuntos aleatórios de treino e teste
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.svm import LinearSVC

import time

#READ FILE WITH DATASET
originalDS = pd.read_csv("weatherHistory.csv", encoding ='latin1')
df = originalDS.copy()
# Table mapping in Precip Type column
precip_type = df.replace(["rain","snow",np.nan],[0,1,2])
df = precip_type
df = df[['Temperature (C)', 
         'Humidity',
         'Wind Speed (km/h)', 
         'Visibility (km)', 
         'Pressure (millibars)', 
         'Precip Type']]

# Defining axis
X = df[['Temperature (C)','Pressure (millibars)','Humidity','Wind Speed (km/h)','Visibility (km)']] 
y = df[['Precip Type']]

In [14]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.22, random_state=42)

lr = LogisticRegression(max_iter=1000, solver="lbfgs")

start = time.time()
lr.fit(X_treino, y_treino)
predict = lr.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)

print('\n\n* Time in seconds: %d' % (time.time() - start))
print("Accuracy: %.2f" % (accuracy * 100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




* Time in seconds: 31
Accuracy: 99.27


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [11]:
confusion_matrix(y_teste, predict)


array([[36523,    71,     0],
       [    0,  4660,     0],
       [  221,     0,     0]])

In [15]:
confusion_matrix(y_teste, predict)


array([[18648,    32,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [13]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     36594
           1       0.98      1.00      0.99      4660
           2       0.00      0.00      0.00       221

    accuracy                           0.99     41475
   macro avg       0.66      0.67      0.66     41475
weighted avg       0.99      0.99      0.99     41475



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.67      0.66     21220
weighted avg       0.99      0.99      0.99     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
linearSVC = LinearSVC()

start = time.time()
linearSVC.fit(X_treino, y_treino)
predict = linearSVC.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)

print('\n\n* Time in seconds: %d' % (time.time() - start))
print("Accuracy: %.2f" % (accuracy * 100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




* Time in seconds: 7
Accuracy: 98.05


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [24]:
confusion_matrix(y_teste, predict)

array([[18390,   290,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [25]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     18680
           1       0.89      1.00      0.94      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.98     21220
   macro avg       0.63      0.66      0.64     21220
weighted avg       0.98      0.98      0.98     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
logreg = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'multi_class': ['ovr', 'multinomial'],

}

linsvm = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'tol': [1e-3, 1e-4, 1e-5],
    'loss': ['hinge', 'squared_hinge'],
    'penalty': ['l1', 'l2' ],
    'multi_class': ['ovr', 'multinomial'],

}

In [0]:
from sklearn.model_selection import GridSearchCV

lr = LogisticRegression(solver='saga')
svm = LinearSVC()

In [30]:
grid_lr = GridSearchCV(lr, logreg)
grid_lr.fit(X_treino, y_treino)

predict = gird_lr.predict(X_teste)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y

NameError: ignored

In [31]:
confusion_matrix(y_teste, predict)

array([[18390,   290,     0],
       [    0,  2417,     0],
       [  123,     0,     0]])

In [32]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     18680
           1       0.89      1.00      0.94      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.98     21220
   macro avg       0.63      0.66      0.64     21220
weighted avg       0.98      0.98      0.98     21220



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
#grid_svm = GridSearchCV(svm, linsvm)
#grid_svm.fit(X_treino, y_treino)

predict = grid_svm.predict(X_teste)
accuracy = accuracy_score(y_teste, predict)
accuracy

0.991894439208294

In [39]:
confusion_matrix(y_teste, predict)

array([[18638,    19,    23],
       [    3,  2410,     4],
       [  123,     0,     0]])

In [36]:
print(classification_report(y_teste, predict))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18680
           1       0.99      1.00      0.99      2417
           2       0.00      0.00      0.00       123

    accuracy                           0.99     21220
   macro avg       0.66      0.66      0.66     21220
weighted avg       0.99      0.99      0.99     21220



In [41]:
grid_lr.best_params_

{'C': 100.0, 'multi_class': 'multinomial', 'penalty': 'l1', 'tol': 0.0001}

In [40]:
grid_svm.best_params_

{'C': 10.0,
 'loss': 'hinge',
 'multi_class': 'ovr',
 'penalty': 'l2',
 'tol': 0.0001}

Busca features
One-vs-All (grid e features)
Rebalanceamento

---

{'C': 10.0,
 'loss': 'hinge',
 'multi_class': 'ovr',
 'penalty': 'l2',
 'tol': 0.0001}